### ISSUE TITLE
cxy_fount: Trying to get more pids than slab_size + 1 always return list of empty lists

### ISSUE THREAD

**Issue by KoFish** [duomark/epocxy#75]
Steps to reproduce (version 1.1.0):
* Create a fount with slab_size=5 and num_slabs=2
* Do cxy_fount:get_pids(FountPid, 7) a couple of times
* Expected result would be to get less pids after a while as the regulator isn't quick enough to refill, instead we get 0 pids for each get_pids call until we request a number of pids that is less than 7.

**Comment by jaynel** [comment]
The fount always returns the number of pids asked for or none.

**Comment by jaynel** [comment]
On thinking about it, there is an issue with having 2 slabs. If you use up one slab, there will often be a partial 2nd slab. So if you ask for close to 2 slabs worth of pids, it will never fill up until you use the partial slab completely without asking for more.

There's not much that can be done about this case, it is a mechanical sympathy problem. If you are asking for 7 pids, the reservoir should have more than 2 slabs of 4 to be responsive. The reservoir depth should allow for spikes that go beyond normal, so I would use a depth of 4 or 5, or use a slab size that is bigger relative to the number of pids normally requested.

As a rough guide: 1) typical (or even maximum) number of pids should be less than one slab, or just slightly more; or 2) use at least 3 slabs. It's a configuration tuning issue.

**Comment by jaynel** [comment]
Solved by https://github.com/duomark/epocxy/pull/76 (not really solved, but not considered an open issue any more). This PR requires 3 slabs in all founts. Best practice is to not ask for more than 2 slabs worth in a single request. If you need more pids, break it into multiple requests or increase the depth or slab size of the fount.
